# Generated by Django 5.2.6 on 2026-09-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('login', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='github_sync.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.PositiveBigIntegerField(unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('webhook_secret', models.BinaryField(help_text='Segredo criptografado com AES-256-GCM')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_repository_name')],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('authored_at', models.DateTimeField(db_index=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('forced_push', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='github_sync.branch')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='github_sync.contributor')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github_sync.repository')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='github_sync.repository'),
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.UUIDField(unique=True)),
                ('event', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='github_sync.repository')),
            ],
        ),
        migrations.CreateModel(
            name='CommitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed')], max_length=10)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='github_sync.commit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('commit', 'path'), name='unique_commit_file')],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='github_sync.contributor')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github_sync.repository')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'number'), name='unique_repository_pr')],
            },
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['repository', 'authored_at'], name='github_sync_reposit_abae5a_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['author', 'authored_at'], name='github_sync_author__121914_idx'),
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('repository', 'sha'), name='unique_repository_commit'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('repository', 'name'), name='unique_repository_branch'),
        ),
    ]
